eslint/eslint-release

lib/release-ops.js, tests/lib/release-ops.js
When generating changelogs or calculating new versions, reverted commits are ignored. For example:
```
* abcd123 Docs: Update something in the docs (githubhandle)
* a1b2c3d Revert "Breaking: A breaking change (fixes #1234)" (Committer Name)
* 321dcba Fix: Fix a bug (fixes #4321) (Abc D. Efg)
* 9876543 Revert "New: Add cool new feature (fixes #42)" (Tina Tester)
* abcdef0 Breaking: A breaking change (fixes #1234) (Cool Committer)
* 1234abc Revert "New: From a previous release (fixes #1234)" (Foo Bar)
* 1234567 New: Add cool new feature (fixes #42) (Toby Testing)
```
Will become:
```
* abcd123 Docs: Update something in the docs (githubhandle)
* 321dcba Fix: Fix a bug (fixes #4321) (Abc D. Efg)
```
And the new version will be a patch bump.
`calculateReleaseFromGitLogs` is only called from …
=> Update: Exclude reverted commits (fixes #3)

CHANGELOG.md, lib/release-ops.js, package.json, tests/lib/release-ops.js
This reverts commit f48c89825a5ea4373208247a3b9d836de6eb09a3.
This reverts commit 6af47e2b925b89ef4e22cad5716869fcb604d03a.
This reverts changes mistakenly pushed as `0.4.0-alpha.5` while confirming the fix for #5.
=> Revert mistakenly pushed 0.4.0-alpha.5 changes

lib/release-ops.js
`package.json` is modified in a subsequent commit through `npm version`
=> Fix: commit only modifies changelog

lib/release-ops.js, tests/lib/release-ops.js
This updates the changelog generator to gracefully handle commit hashes longer than 7 characters. Long shorthashes like this can be produced by newer versions of git when working with a large repository. Previously, the release tool would skip any commits with long hashes (resulting in an empty changelog).
With this implementation, the long shorthashes will be included in the changelog rather than being truncated. One disadvantage of doing it this way is that the changelog might be inconsistent -- it could vary between 7-character and 8-character shorthashes depending on the version of git installed on the release machine. However, this does reduce the risk of generating broken links due to ambiguous commit hashes, which is the whole point of having longer shorthashes anyway.
Fixes …
=> Fix: gracefully handle shorthashes longer than 7 characters (fixes #15)

bin/eslint-prerelease.js
This will make it easier to do prereleases of packages like `espree` from CI.
=> Update: publish release notes to GitHub when doing a prerelease

lib/release-ops.js
GitHub has a feature where releases can be marked as "prereleases", which slightly changes how they are displayed. This updates the release tool to apply that marking when the current release is a prerelease.
=> Fix: Mark prerelease notes as "prereleases" on GitHub

lib/release-ops.js, tests/lib/release-ops.js
This updates the changelog generator to link to commits on GitHub when generating changelogs. This should also fix the issue where commit shorthashes are ambiguous, resulting in a 404 in links from generated blogposts for ESLint.
=> Update: include links to commits on GitHub in changelogs

lib/shell-ops.js
This prevents the npm 2FA code from being printed to standard output. As a result, an attacker who had compromised an npm access token and also had access to build output would no longer be able to obtain a TOTP and use it in the next 30 seconds.
I tested this by generating a release locally and then running `npm run publish-release`. As expected, the TOTP was redacted in the output (and then the release failed without doing anything because I supplied an invalid access token for the test).
=> Update: avoid printing TOTP to output when publishing

.eslintrc.yml, .travis.yml, bin/eslint-generate-prerelease.js, bin/eslint-generate-release.js, bin/eslint-publish-release.js, lib/release-ops.js, lib/shell-ops.js, package.json, tests/lib/release-ops.js, tests/lib/shell-ops.js
+ dorp support 0.x 4.x
+ upgrade some deps
=> Breaking: require node >= 8.0 & upgrade eslint-config-eslint

lib/release-ops.js, tests/lib/release-ops.js
For a new stable release following a prerelease sequence, the changelog will include the commits for all of the prereleases going back to the last stable release. For example, given the following release sequence:
- 6.7.8
- 6.8.0
- 7.0.0-alpha.0
- 7.0.0-alpha.1
- 7.0.0
The `7.0.0` changelog will include all changes since `6.8.0`, whereas the `7.0.0-alpha.1` changelog will include only changes since `7.0.0-alpha.0`.
If we prefer to include all changes going back to the previous stable release even for prerelease changelogs, that's an easy change and actually simplifies the logic a bit.
=> Update: Major version changelogs include all prereleases

lib/release-ops.js
`ReleaseOps.writeChangelog()` is currently broken because the local-import `shelljs` module doesn't add `String.prototype.to()`. I'm honestly not sure how this ever worked - I tried locking the version of `shelljs` to 0.8.3 and 0.8.2 and the problem persisted in both (we have `^0.8.3` in `package.json`).
I'll follow up with another PR after the 7.0.0 release that goes back to the local-import `shelljs` module and adds tests for `writeChangelog()` (we currently don't have any).
=> Fix: use global-import shelljs

lib/release-ops.js
Add blank line between changelog and last version in the changelog.
fixes https://github.com/eslint/eslint/pull/13396
=> Fix: add blank line between changelog and last version

.github/workflows/ci.yml, package.json
Accidentally pushed https://github.com/eslint/eslint-release/commit/60eb52884c9d5a4e51001110d216959cc3974e57 to `master` before I could catch this typo (I usually push to GitHub to review the changes in the GitHub view). Sorry about that!
=> Fix: typo in GitHub Actions CI workflow

.github/workflows/ci.yml, package.json
This PR drops support for Node 8 now that it's no longer supported by the Node team.
=> Breaking: drop support for Node <10

lib/release-ops.js
This removes the `origin master` part of the `git push` command during a release. This should allow us to use the current branch instead of always `master`, which will facilitate the change over to using `main` as the primary branch.
=> Update: Remove specific branch from git push (fixes #42)

lib/release-ops.js, tests/lib/release-ops.js
This PR implements #46.
Based on [eslint/eslint:/templates/blogpost.md.ejs](https://github.com/eslint/eslint/blob/master/templates/blogpost.md.ejs).
=> Update: group commits by types in release log (fixes #46)

lib/shell-ops.js
Tests were not passing in my environment while implementing #47.
I am using windows and my path env name was `Path` (not `PATH`).
This caused `env.PATH` to be `undefined`.
Accessing `process.env.PATH` returns the correct value.
This PR fixes this by handling all env names as uppercased names in windows.
=> Fix: env var names are case-insensitive in windows

README.md
This updates the README to reflect how this tool actually works.
=> Docs: Update README to reflect reality (fixes #36)

.eslintrc.yml, .github/workflows/ci.yml, package.json
Upgrades `eslint-config-eslint` to v7.0.0, `eslint-plugin-node` to 11.1.0.
Adds `eslint-plugin-jsdoc`, since it is required by the new `eslint-config-eslint`.
Adds Node 15.x and 16.x to test matrix.
=> Chore: upgrade eslint-config-eslint@7.0.0

lib/release-ops.js, tests/lib/release-ops.js
This change allows eslint-release to interpret conventional commit-style commit messages to generate the correct release information. This will allow us to transition from our own commit message style into conventional commits without disrupting our releases.
Note: Conventional commits uses "feat" to be equivalent to both "New" and "Update" for us. For simplicity, I decided to map "feat" to "New".
=> Update: Support conventional commits

lib/release-ops.js, package.json, tests/lib/release-ops.js
This PR removes the dependency shelljs and replaces its usages with native Node.js API calls. It also adds unit tests to ensure that the behavior of `writeChangelog()` hasn't changed.
ShellJS in versions prior to 0.8.5 has a high rated vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2022-0144.
=> chore: remove dependency shelljs

.github/workflows/ci.yml, README.md, lib/release-ops.js
Refs https://github.com/eslint/eslint/issues/18691
Adds support for releasing new versions of previous major lines.
* Code that calculates changelog will use the latest version tag of those that point to the history of the current branch only. That should ensure that the changelog and the version to be released are correctly calculated.
* `generateRelease()` will have an optional parameter `packageTag`. When releasing, for example, v8.57.1 (the current latest version is v9.9.1), eslint's `Makefile.js` will pass `"maintenance"`. This tag will be used as `--tag` for `npm publish`. This tag will also be used to determine whether GitHub should mark the GitHub release as Latest.
Marked as a draft to do some testing first.
=> feat: Support updates to previous major versions

package.json, tests/lib/release-ops.js, tests/lib/shell-ops.js
Hello,
This PR is the follow up PR of https://github.com/eslint/markdown/issues/350.
I've replaced `chai` with Node.js `assert` module to reduce dependency footprint.
=> test: replace `chai` with Node.js `assert` to reduce dependency
